[versions]
agp = "8.9.0"
android-compileSdk = "34"
android-minSdk = "26"
android-targetSdk = "34"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.8.4"
androidx-startup-runtime = "1.2.0"
compose-plugin = "1.7.3"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.1"
dl-common = "0.5.4"
dl-app = "2.5.9"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup-runtime" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
dl-common = { module = "com.github.D10NGYANG:DLCommonUtil", version.ref = "dl-common" }
dl-app = { module = "com.github.D10NGYANG:DLAppUtil", version.ref = "dl-app" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }